module org.ashot.shellflow {
    requires javafx.fxml;
    requires atlantafx.base;
    requires org.slf4j;
    requires org.controlsfx.controls;
    requires com.techsenger.jeditermfx.ui;
    requires com.techsenger.jeditermfx.core;
    requires pty4j;
    requires org.jetbrains.annotations;
    requires java.desktop;
    requires com.dustinredmond.fxtrayicon;
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.base;
    requires com.fasterxml.jackson.databind;
    requires jdk.management;

    exports org.ashot.shellflow;
    exports org.ashot.shellflow.node.popup;
    opens org.ashot.shellflow to javafx.fxml;
    opens org.ashot.shellflow.node.popup to javafx.fxml;
    exports org.ashot.shellflow.registry;
    opens org.ashot.shellflow.registry to javafx.fxml;
    exports org.ashot.shellflow.utils;
    opens org.ashot.shellflow.data.constant to javafx.base;
    opens org.ashot.shellflow.node.icon to javafx.base;
    opens org.ashot.shellflow.data.message to javafx.fxml;
    opens org.ashot.shellflow.utils to javafx.base, javafx.fxml;
    exports org.ashot.shellflow.data.command;
    opens org.ashot.shellflow.node.toolbar to javafx.base;
    exports org.ashot.shellflow.data.constant;
    exports org.ashot.shellflow.config;
    exports org.ashot.shellflow.mapper;
    exports org.ashot.shellflow.node.entry;
    exports org.ashot.shellflow.data.entry;
    exports org.ashot.shellflow.controller;
    opens org.ashot.shellflow.controller to javafx.fxml;
    opens org.ashot.shellflow.node.entry to javafx.base;
    exports org.ashot.shellflow.node.entry.field;
    opens org.ashot.shellflow.node.entry.field to javafx.base;
    exports org.ashot.shellflow.node.execution.tab;
    opens org.ashot.shellflow.node.execution.tab to javafx.base;
    opens org.ashot.shellflow.data.entry to com.fasterxml.jackson.databind;
    opens org.ashot.shellflow.data.variable to com.fasterxml.jackson.databind;
    opens org.ashot.shellflow.data.util to com.fasterxml.jackson.databind;
    exports org.ashot.shellflow.data.execution;
    opens org.ashot.shellflow.data.execution to com.fasterxml.jackson.databind;
    exports org.ashot.shellflow.data.variable;
    opens org.ashot.shellflow.mapper to javafx.base, javafx.fxml;
    exports org.ashot.shellflow.execution.manager;
    opens org.ashot.shellflow.execution.manager to javafx.base;
    exports org.ashot.shellflow.exception.io;
    exports org.ashot.shellflow.exception.execution;
    exports org.ashot.shellflow.exception.app;
    exports org.ashot.shellflow.exception.entry;
    exports org.ashot.shellflow.execution.task.single;
    opens org.ashot.shellflow.execution.task.single to javafx.base;
    exports org.ashot.shellflow.execution.task.sequence;
    opens org.ashot.shellflow.execution.task.sequence to javafx.base;
    exports org.ashot.shellflow.node.execution;
    opens org.ashot.shellflow.node.execution to javafx.base;
}
