module org.ashot.shellflow {
    requires javafx.fxml;
    requires atlantafx.base;
    requires org.json;
    requires org.slf4j;
    requires org.controlsfx.controls;
    requires org.fxmisc.richtext;
    requires org.fxmisc.flowless;
    requires reactfx;
    requires com.techsenger.jeditermfx.ui;
    requires com.techsenger.jeditermfx.core;
    requires pty4j;
    requires org.jetbrains.annotations;
    requires java.desktop;
    requires com.dustinredmond.fxtrayicon;
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.base;

    exports org.ashot.shellflow;
    exports org.ashot.shellflow.exception;
    exports org.ashot.shellflow.node.popup;
    opens org.ashot.shellflow to javafx.fxml;
    opens org.ashot.shellflow.node.popup to javafx.fxml;
    exports org.ashot.shellflow.registry;
    opens org.ashot.shellflow.registry to javafx.fxml;
    exports org.ashot.shellflow.utils;
    opens org.ashot.shellflow.data.constant to javafx.base;
    opens org.ashot.shellflow.node.icon to javafx.base;
    opens org.ashot.shellflow.data.message to javafx.fxml;
    opens org.ashot.shellflow.utils to javafx.base, javafx.fxml;
    exports org.ashot.shellflow.data.command;
    opens org.ashot.shellflow.node.toolbar to javafx.base;
    exports org.ashot.shellflow.data.constant;
    exports org.ashot.shellflow.config;
    exports org.ashot.shellflow.mapper;
    exports org.ashot.shellflow.node.entry;
    exports org.ashot.shellflow.data.entry;
    exports org.ashot.shellflow.controller;
    opens org.ashot.shellflow.controller to javafx.fxml;
    exports org.ashot.shellflow.execution.task;
    exports org.ashot.shellflow.execution.task.factory;
    opens org.ashot.shellflow.node.entry to javafx.base;
    exports org.ashot.shellflow.node.entry.field;
    opens org.ashot.shellflow.node.entry.field to javafx.base;
    opens org.ashot.shellflow.execution.task to javafx.base;
    exports org.ashot.shellflow.execution.tab;
    opens org.ashot.shellflow.execution.tab to javafx.base;
}
